// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package template

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Add() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<h1 class=\"title is-2\">Add Query</h1><form hx-post=\"/query\" hx-target=\"#errorZone\" id=\"queryForm\"><div class=\"field\"><label class=\"label\">Name</label><div class=\"control\"><input class=\"input\" name=\"queryName\" type=\"text\" type=\"text\" placeholder=\"Query Name\"></div></div><div class=\"field\"><label class=\"label\">Message</label><div class=\"control\"><textarea class=\"textarea\" name=\"query\" type=\"text\" placeholder=\"Query\" id=\"queryThing\" onchange=\"format(this)\"></textarea></div></div><div class=\"field is-grouped\"><div class=\"control\"><button class=\"button is-link\" type=\"submit\" value=\"Add Query\">Add Query</button></div></div></form><script>\n  function format(event) {\n    var format = window.sqlFormatter.format;\n    event.value = format(event.value)\n  }\n\n  document.addEventListener(\"htmx:afterRequest\", () => {\n    document.getElementById(\"queryForm\").reset();\n  })\n</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
